# Generated by Django 5.1.4 on 2025-01-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['fullname_shipping'], 'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address1_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='address2_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='city_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='country_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='county_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='email_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='names',
            new_name='fullname_shipping',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode',
            new_name='postalcode_shipping',
        ),
    ]
