# Generated by Django 5.1.4 on 2025-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['names'], 'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1_shipping',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2_shipping',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city_shipping',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county_shipping',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email_shipping',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullname_shipping',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode_shipping',
            new_name='postalcode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country_shipping',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='United States', max_length=250),
        ),
    ]
