# Generated by Django 5.1.4 on 2025-01-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['full_name'], 'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='names',
            new_name='full_name',
        ),
    ]
