# Generated by Django 5.1.4 on 2025-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prev_cart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
